//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.TestData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartridgeLoad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartridgeLoad()
        {
            this.Cartridges = new HashSet<Cartridge>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CaliberId { get; set; }
        public int BulletId { get; set; }
        public Nullable<int> PowderId { get; set; }
        public Nullable<decimal> PowderWeight { get; set; }
        public Nullable<int> PowderWeightUnitId { get; set; }
        public decimal COL { get; set; }
        public int COLUnitId { get; set; }
        public Nullable<int> Velocity { get; set; }
        public Nullable<int> VelocityUnitId { get; set; }
        public Nullable<int> Pressure { get; set; }
        public Nullable<int> PressureUnitId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartridge> Cartridges { get; set; }
    }
}
