//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.TestData
{
    using System;
    using System.Collections.Generic;
    
    public partial class GunImage
    {
        public int Id { get; set; }
        public int GunId { get; set; }
        public string PictureLocation { get; set; }
    
        public virtual Gun Gun { get; set; }
    }
}
