//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.TestData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Powder()
        {
            this.PowderCosts = new HashSet<PowderCost>();
            this.PowderQuantities = new HashSet<PowderQuantity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ManufacturerId { get; set; }
        public int PowderTypeId { get; set; }
        public int PowderShapeId { get; set; }
        public string Notes { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual PowderShape PowderShape { get; set; }
        public virtual PowderType PowderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PowderCost> PowderCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PowderQuantity> PowderQuantities { get; set; }
    }
}
