//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.TestData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShootingSession
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int LocationId { get; set; }
        public int GunId { get; set; }
        public int CartridgeId { get; set; }
        public int Rounds { get; set; }
        public Nullable<int> Retention { get; set; }
        public string Notes { get; set; }
    
        public virtual Cartridge Cartridge { get; set; }
        public virtual Gun Gun { get; set; }
        public virtual ShootingLocation ShootingLocation { get; set; }
    }
}
