//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.EFData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShootingEntities1 : DbContext
    {
        public ShootingEntities1()
            : base("name=ShootingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrassView> BrassViews { get; set; }
        public virtual DbSet<BulletView> BulletViews { get; set; }
        public virtual DbSet<CaliberView> CaliberViews { get; set; }
        public virtual DbSet<CartridgeLoadView> CartridgeLoadViews { get; set; }
        public virtual DbSet<CartridgeView> CartridgeViews { get; set; }
        public virtual DbSet<GunsCalibersView> GunsCalibersViews { get; set; }
        public virtual DbSet<GunView> GunViews { get; set; }
        public virtual DbSet<PowderView> PowderViews { get; set; }
        public virtual DbSet<PrimerView> PrimerViews { get; set; }
        public virtual DbSet<ShootingLocationView> ShootingLocationViews { get; set; }
        public virtual DbSet<ShootingSessionView> ShootingSessionViews { get; set; }
        public virtual DbSet<UnitView> UnitViews { get; set; }
    }
}
