//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.EFData
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Plural { get; set; }
        public string Abbreviation { get; set; }
        public int UnitTypeId { get; set; }
        public string UnitTypeName { get; set; }
        public string UnitTypeNotes { get; set; }
        public string Notes { get; set; }
    }
}
