//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brass()
        {
            this.BrassCosts = new HashSet<BrassCost>();
            this.BrassQuantities = new HashSet<BrassQuantity>();
            this.Cartridges = new HashSet<Cartridge>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public int CaliberId { get; set; }
        public decimal Length { get; set; }
        public int LengthUnitId { get; set; }
        public int MaterialId { get; set; }
        public int ManufacturerId { get; set; }
        public int TimesFired { get; set; }
        public string Notes { get; set; }
    
        public virtual Caliber Caliber { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Material Material { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrassCost> BrassCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrassQuantity> BrassQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartridge> Cartridges { get; set; }
    }
}
