//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bullet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bullet()
        {
            this.BulletCosts = new HashSet<BulletCost>();
            this.BulletQuantities = new HashSet<BulletQuantity>();
            this.CartridgeLoads = new HashSet<CartridgeLoad>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BulletTypeId { get; set; }
        public int MaterialId { get; set; }
        public decimal Diameter { get; set; }
        public int DiameterUnitId { get; set; }
        public int Mass { get; set; }
        public int MassUnitId { get; set; }
        public Nullable<decimal> SectionalDensity { get; set; }
        public Nullable<decimal> BallisticCoefficient { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<int> LengthUnitId { get; set; }
        public int ManufacturerId { get; set; }
        public string Notes { get; set; }
    
        public virtual BulletType BulletType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Material Material { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
        public virtual Unit Unit2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulletCost> BulletCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulletQuantity> BulletQuantities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartridgeLoad> CartridgeLoads { get; set; }
    }
}
