//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartridgeLoadView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CartridgeLoadName { get; set; }
        public int CaliberId { get; set; }
        public string CaliberViewName { get; set; }
        public Nullable<decimal> CaliberViewDiameter { get; set; }
        public Nullable<int> CaliberViewDiameterUnitId { get; set; }
        public string CaliberViewDiameterUnitViewName { get; set; }
        public string CaliberViewDiameterUnitViewPlural { get; set; }
        public string CaliberViewDiameterUnitViewAbbreviation { get; set; }
        public Nullable<int> CaliberViewDiameterUnitViewUnitTypeId { get; set; }
        public string CaliberViewDiameterUnitViewUnitTypeName { get; set; }
        public string CaliberViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string CaliberViewDiameterUnitViewNotes { get; set; }
        public Nullable<int> CaliberViewPrimerTypeId { get; set; }
        public string CaliberViewPrimerTypeName { get; set; }
        public string CaliberViewPrimerTypeAbbreviation { get; set; }
        public string CaliberViewPrimerTypeNotes { get; set; }
        public Nullable<int> CaliberViewSortOrder { get; set; }
        public string CaliberViewNotes { get; set; }
        public int BulletId { get; set; }
        public string BulletViewName { get; set; }
        public string BulletViewBulletName { get; set; }
        public string BulletViewBulletFullName { get; set; }
        public Nullable<int> BulletViewBulletTypeId { get; set; }
        public string BulletViewBulletTypeName { get; set; }
        public string BulletViewBulletTypeAbbreviation { get; set; }
        public string BulletViewBulletTypeNotes { get; set; }
        public Nullable<int> BulletViewMaterialId { get; set; }
        public string BulletViewMaterialName { get; set; }
        public string BulletViewMaterialNotes { get; set; }
        public Nullable<decimal> BulletViewDiameter { get; set; }
        public Nullable<int> BulletViewDiameterUnitId { get; set; }
        public string BulletViewDiameterUnitViewName { get; set; }
        public string BulletViewDiameterUnitViewPlural { get; set; }
        public string BulletViewDiameterUnitViewAbbreviation { get; set; }
        public Nullable<int> BulletViewDiameterUnitViewUnitTypeId { get; set; }
        public string BulletViewDiameterUnitViewUnitTypeName { get; set; }
        public string BulletViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string BulletViewDiameterUnitViewNotes { get; set; }
        public Nullable<int> BulletViewMass { get; set; }
        public Nullable<int> BulletViewMassUnitId { get; set; }
        public string BulletViewMassUnitViewName { get; set; }
        public string BulletViewMassUnitViewPlural { get; set; }
        public string BulletViewMassUnitViewAbbreviation { get; set; }
        public Nullable<int> BulletViewMassUnitViewUnitTypeId { get; set; }
        public string BulletViewMassUnitViewUnitTypeName { get; set; }
        public string BulletViewMassUnitViewUnitTypeNotes { get; set; }
        public string BulletViewMassUnitViewNotes { get; set; }
        public Nullable<decimal> BulletViewSectionalDensity { get; set; }
        public Nullable<decimal> BulletViewBallisticCoefficient { get; set; }
        public Nullable<decimal> BulletViewLength { get; set; }
        public Nullable<int> BulletViewLengthUnitId { get; set; }
        public string BulletViewLengthUnitViewName { get; set; }
        public string BulletViewLengthUnitViewPlural { get; set; }
        public string BulletViewLengthUnitViewAbbreviation { get; set; }
        public Nullable<int> BulletViewLengthUnitViewUnitTypeId { get; set; }
        public string BulletViewLengthUnitViewUnitTypeName { get; set; }
        public string BulletViewLengthUnitViewUnitTypeNotes { get; set; }
        public string BulletViewLengthUnitViewNotes { get; set; }
        public Nullable<int> BulletViewManufacturerId { get; set; }
        public string BulletViewManufacturerName { get; set; }
        public string BulletViewManufacturerAddress { get; set; }
        public string BulletViewManufacturerCity { get; set; }
        public string BulletViewManufacturerState { get; set; }
        public string BulletViewManufacturerZip { get; set; }
        public string BulletViewManufacturerURL { get; set; }
        public string BulletViewManufacturerNotes { get; set; }
        public string BulletViewNotes { get; set; }
        public Nullable<int> PowderId { get; set; }
        public string PowderViewName { get; set; }
        public string PowderViewPowderName { get; set; }
        public Nullable<int> PowderViewManufacturerId { get; set; }
        public string PowderViewManufacturerName { get; set; }
        public string PowderViewManufacturerAddress { get; set; }
        public string PowderViewManufacturerCity { get; set; }
        public string PowderViewManufacturerState { get; set; }
        public string PowderViewManufacturerZip { get; set; }
        public string PowderViewManufacturerURL { get; set; }
        public string PowderViewManufacturerNotes { get; set; }
        public Nullable<int> PowderViewPowderTypeId { get; set; }
        public string PowderViewPowderTypeName { get; set; }
        public string PowderViewPowderTypeNotes { get; set; }
        public Nullable<int> PowderViewPowderShapeId { get; set; }
        public string PowderViewPowderShapeName { get; set; }
        public string PowderViewPowderShapeNotes { get; set; }
        public string PowderViewNotes { get; set; }
        public Nullable<int> PowderWeight { get; set; }
        public Nullable<int> PowderWeightUnitId { get; set; }
        public string PowderWeightUnitViewName { get; set; }
        public string PowderWeightUnitViewPlural { get; set; }
        public string PowderWeightUnitViewAbbreviation { get; set; }
        public Nullable<int> PowderWeightUnitViewUnitTypeId { get; set; }
        public string PowderWeightUnitViewUnitTypeName { get; set; }
        public string PowderWeightUnitViewUnitTypeNotes { get; set; }
        public string PowderWeightUnitViewNotes { get; set; }
        public decimal COL { get; set; }
        public int COLUnitId { get; set; }
        public string COLUnitViewName { get; set; }
        public string COLUnitViewPlural { get; set; }
        public string COLUnitViewAbbreviation { get; set; }
        public Nullable<int> COLUnitViewUnitTypeId { get; set; }
        public string COLUnitViewUnitTypeName { get; set; }
        public string COLUnitViewUnitTypeNotes { get; set; }
        public string COLUnitViewNotes { get; set; }
        public Nullable<int> Velocity { get; set; }
        public Nullable<int> VelocityUnitId { get; set; }
        public string VelocityUnitViewName { get; set; }
        public string VelocityUnitViewPlural { get; set; }
        public string VelocityUnitViewAbbreviation { get; set; }
        public Nullable<int> VelocityUnitViewUnitTypeId { get; set; }
        public string VelocityUnitViewUnitTypeName { get; set; }
        public string VelocityUnitViewUnitTypeNotes { get; set; }
        public string VelocityUnitViewNotes { get; set; }
        public Nullable<int> Pressure { get; set; }
        public Nullable<int> PressureUnitId { get; set; }
        public string PressureUnitViewName { get; set; }
        public string PressureUnitViewPlural { get; set; }
        public string PressureUnitViewAbbreviation { get; set; }
        public Nullable<int> PressureUnitViewUnitTypeId { get; set; }
        public string PressureUnitViewUnitTypeName { get; set; }
        public string PressureUnitViewUnitTypeNotes { get; set; }
        public string PressureUnitViewNotes { get; set; }
        public string Notes { get; set; }
    }
}
