//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gun()
        {
            this.GunImages = new HashSet<GunImage>();
            this.GunsCalibers = new HashSet<GunsCaliber>();
            this.ShootingSessions = new HashSet<ShootingSession>();
        }
    
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public int CaliberId { get; set; }
        public int ManufacturerId { get; set; }
        public int Capacity { get; set; }
        public decimal BarrelLength { get; set; }
        public int LengthUnitId { get; set; }
        public int GunTypeId { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime AcquisitionDate { get; set; }
        public Nullable<System.DateTime> RetireDate { get; set; }
        public string Details { get; set; }
        public string Notes { get; set; }
    
        public virtual Caliber Caliber { get; set; }
        public virtual GunType GunType { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GunImage> GunImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GunsCaliber> GunsCalibers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShootingSession> ShootingSessions { get; set; }
    }
}
