//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingManager.DataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gun1
    {
        public int Id { get; set; }
        public string SerialNumber { get; set; }
        public string Name { get; set; }
        public int CaliberId { get; set; }
        public int ManufacturerId { get; set; }
        public int Capacity { get; set; }
        public decimal BarrelLength { get; set; }
        public int LengthUnitId { get; set; }
        public int GunTypeId { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime AcquisitionDate { get; set; }
        public System.DateTime RetireDate { get; set; }
        public string Details { get; set; }
        public string Notes { get; set; }
    }
}
