//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikeHistory
    {
        public int Id { get; set; }
        public int BikeId { get; set; }
        public string Frame { get; set; }
        public string Fork { get; set; }
        public string WheelSet { get; set; }
        public string Shifters { get; set; }
        public string Brakes { get; set; }
        public string Cassette { get; set; }
        public string CrankSet { get; set; }
        public string BottomBracket { get; set; }
        public string FrontDerailleur { get; set; }
        public string RearDerailleur { get; set; }
        public string Pedals { get; set; }
        public string Headset { get; set; }
        public string Stem { get; set; }
        public string HandleBars { get; set; }
        public string SeatPost { get; set; }
        public string Saddle { get; set; }
        public string Notes { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Bike Bike { get; set; }
    }
}
