//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BikePart
    {
        public int Id { get; set; }
        public int BikeId { get; set; }
        public int PartId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int OdometerReading { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Bike Bike1 { get; set; }
        public virtual Part Part { get; set; }
        public virtual Part Part1 { get; set; }
    }
}
