//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenchmarkMile> BenchmarkMiles { get; set; }
        public virtual DbSet<Bike> Bikes { get; set; }
        public virtual DbSet<BikeHistory> BikeHistories { get; set; }
        public virtual DbSet<BikeOnlyMile> BikeOnlyMiles { get; set; }
        public virtual DbSet<BikePart> BikeParts { get; set; }
        public virtual DbSet<BikeType> BikeTypes { get; set; }
        public virtual DbSet<Circuit> Circuits { get; set; }
        public virtual DbSet<CircuitComponent> CircuitComponents { get; set; }
        public virtual DbSet<CircuitsComponent> CircuitsComponents { get; set; }
        public virtual DbSet<ExerciseType> ExerciseTypes { get; set; }
        public virtual DbSet<HRZone> HRZones { get; set; }
        public virtual DbSet<HRZoneTime> HRZoneTimes { get; set; }
        public virtual DbSet<LiftingSession> LiftingSessions { get; set; }
        public virtual DbSet<Maintenance> Maintenances { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<MissedMile> MissedMiles { get; set; }
        public virtual DbSet<NonRideMile> NonRideMiles { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartType> PartTypes { get; set; }
        public virtual DbSet<RecreationalRide> RecreationalRides { get; set; }
        public virtual DbSet<RecreationalRideGPX> RecreationalRideGPXes { get; set; }
        public virtual DbSet<RecreationalRun> RecreationalRuns { get; set; }
        public virtual DbSet<RecreationalRunGPX> RecreationalRunGPXes { get; set; }
        public virtual DbSet<RecreationalWalk> RecreationalWalks { get; set; }
        public virtual DbSet<RecreationalWalkGPX> RecreationalWalkGPXes { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteDirection> RouteDirections { get; set; }
        public virtual DbSet<RouteDisplay> RouteDisplays { get; set; }
        public virtual DbSet<RoutePicture> RoutePictures { get; set; }
        public virtual DbSet<RouteType> RouteTypes { get; set; }
        public virtual DbSet<Shoe> Shoes { get; set; }
        public virtual DbSet<ShoeType> ShoeTypes { get; set; }
        public virtual DbSet<Stair> Stairs { get; set; }
        public virtual DbSet<StationaryRide> StationaryRides { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TrainingRide> TrainingRides { get; set; }
        public virtual DbSet<TrainingRideGPX> TrainingRideGPXes { get; set; }
        public virtual DbSet<TrainingRun> TrainingRuns { get; set; }
        public virtual DbSet<TrainingRunGPX> TrainingRunGPXes { get; set; }
        public virtual DbSet<TrainingWalk> TrainingWalks { get; set; }
        public virtual DbSet<TrainingWalkGPX> TrainingWalkGPXes { get; set; }
        public virtual DbSet<TreadmillRun> TreadmillRuns { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
        public virtual DbSet<MaintenanceLog> MaintenanceLogs { get; set; }
        public virtual DbSet<Part1> Parts1 { get; set; }
        public virtual DbSet<RecreationalRide1> RecreationalRides1 { get; set; }
        public virtual DbSet<RecreationalRun1> RecreationalRuns1 { get; set; }
        public virtual DbSet<RecreationalWalk1> RecreationalWalks1 { get; set; }
        public virtual DbSet<StationaryRide1> StationaryRides1 { get; set; }
        public virtual DbSet<TrainingRide1> TrainingRides1 { get; set; }
        public virtual DbSet<TrainingRun1> TrainingRuns1 { get; set; }
        public virtual DbSet<TrainingWalk1> TrainingWalks1 { get; set; }
        public virtual DbSet<TreadmillRun1> TreadmillRuns1 { get; set; }
    }
}
