//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRZoneTime
    {
        public int Id { get; set; }
        public int ZoneId { get; set; }
        public int RideId { get; set; }
        public int ZoneHours { get; set; }
        public int ZoneMinutes { get; set; }
        public int ZoneSeconds { get; set; }
    
        public virtual HRZone HRZone { get; set; }
        public virtual TrainingRide TrainingRide { get; set; }
    }
}
