//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceLog
    {
        public System.DateTime Operation_Date { get; set; }
        public string Bike { get; set; }
        public string Manufacturer { get; set; }
        public string Part { get; set; }
        public string Part_Type { get; set; }
        public string Action_Taken { get; set; }
        public int Odometer { get; set; }
        public string Notes { get; set; }
    }
}
