//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part1
    {
        public int Id { get; set; }
        public string Manufacturer { get; set; }
        public string Part_Name { get; set; }
        public string Part_Type { get; set; }
    }
}
