//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecreationalRide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecreationalRide()
        {
            this.RecreationalRideGPXes = new HashSet<RecreationalRideGPX>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int StartOdometer { get; set; }
        public int EndOdometer { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int RideTimeHours { get; set; }
        public int RideTimeMinutes { get; set; }
        public int RideTimeSeconds { get; set; }
        public System.DateTime BikeEndTime { get; set; }
        public int BikeTimeHours { get; set; }
        public int BikeTimeMinutes { get; set; }
        public int BikeTimeSeconds { get; set; }
        public int AverageHR { get; set; }
        public int MaxHR { get; set; }
        public int AverageCadence { get; set; }
        public int ElevationGain { get; set; }
        public decimal MaxSpeed { get; set; }
        public string Wind { get; set; }
        public int Temperature { get; set; }
        public bool Precipitation { get; set; }
        public int BikeId { get; set; }
        public int RouteId { get; set; }
        public string Notes { get; set; }
    
        public virtual Bike Bike { get; set; }
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecreationalRideGPX> RecreationalRideGPXes { get; set; }
    }
}
