//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecreationalWalk1
    {
        public int Id { get; set; }
        public System.DateTime Walk_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public System.DateTime Path_Ending_Time { get; set; }
        public int Hours { get; set; }
        public int Minutes { get; set; }
        public int Seconds { get; set; }
        public int Path_Hours { get; set; }
        public int Path_Minutes { get; set; }
        public int Path_Seconds { get; set; }
        public decimal Distance { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<decimal> Pace { get; set; }
        public Nullable<decimal> Overall_Speed { get; set; }
        public Nullable<decimal> Overall_Pace { get; set; }
        public decimal Maximum_Speed { get; set; }
        public int Average_HR { get; set; }
        public int Maximum_HR { get; set; }
        public int Elevation_Gain { get; set; }
        public string Wind { get; set; }
        public int Temperature { get; set; }
        public bool Precipitation { get; set; }
        public string Shoe_Name { get; set; }
        public string Shoe_Type { get; set; }
        public string Route_Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Route_Type { get; set; }
        public string Notes { get; set; }
        public string GPX_ { get; set; }
    }
}
