//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutePicture
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public string ImageFileName { get; set; }
        public string ImageDescription { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
