//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StationaryRide1
    {
        public int Id { get; set; }
        public System.DateTime Ride_Date { get; set; }
        public System.DateTime Starting_Time { get; set; }
        public System.DateTime Ending_Time { get; set; }
        public int Hours { get; set; }
        public int Minutes { get; set; }
        public int Seconds { get; set; }
        public Nullable<int> Distance { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public Nullable<decimal> Pace { get; set; }
        public int Average_HR { get; set; }
        public int Maximum_HR { get; set; }
        public int Average_Cadence { get; set; }
        public string Notes { get; set; }
        public string Bike_Name { get; set; }
        public string Bike_Type { get; set; }
    }
}
