//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Weight1 { get; set; }
        public decimal BodyFatPercentage { get; set; }
        public string Notes { get; set; }
    }
}
